<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AXSharp.Abstractions" Version="0.19.0-alpha.203" />
    <PackageReference Include="AXSharp.Connector" Version="0.19.0-alpha.203" />
    <PackageReference Include="AXSharp.Connector.S71500.WebAPI" Version="0.19.0-alpha.203" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include=".g\**" />
  </ItemGroup>
</Project>