<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net9.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AXSharp.Abstractions" Version="0.20.0-341--NEW-FEATURE-Poco-types-should-be-rather-placed-into-onlinenamespace-Poco-instead-of-Poco-onlinenamespace.257" />
		<PackageReference Include="AXSharp.Connector" Version="0.20.0-341--NEW-FEATURE-Poco-types-should-be-rather-placed-into-onlinenamespace-Poco-instead-of-Poco-onlinenamespace.257" />
	</ItemGroup>

	<ItemGroup>
    	<Compile Include=".g\**" />
  	</ItemGroup>

	<ItemGroup>
		<Folder Include=".meta\" />
		<Content Include=".meta\**" />
	</ItemGroup>
</Project>