<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    

	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>

	  <!--NuGet Specific part-->
	  <Description>Sets of essential presentation controls for AX# - Blazor</Description>

	  <!-- NuGet Common part-->
	  <PackageProjectUrl>https://github.com/inxton/</PackageProjectUrl>
	  <RepositoryUrl>https://github.com/inxton/axsharp</RepositoryUrl>
	  <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	  <Authors>inxton</Authors>
	  <Copyright>(c) MTS spol. s r.o. and Contributors</Copyright>
	  <PackageTags>simatix-ax, PLC, industrial automation, SCADA, HMI</PackageTags>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
	  <Title>AX# Essential UI control Blazor</Title>
	  <PackageIcon>icon_128_128.png</PackageIcon>
	  <RepositoryType>git</RepositoryType>
	  <IncludeSymbols>True</IncludeSymbols>
	  <SymbolPackageFormat>snupkg</SymbolPackageFormat>
	  <PackageLicenseExpression>MIT</PackageLicenseExpression>
	  <PackageReleaseNotes>
		  Release notes are published here:
		  https://github.com/inxton/axsharp/releases
	  </PackageReleaseNotes>
	  <PackageReadmeFile>NUGET-README.md</PackageReadmeFile>
    
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net6.0|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net7.0|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="RenderableContentControl\**" />
    <Compile Remove="wwwroot\**" />
    <Content Remove="RenderableContentControl\**" />
    <Content Remove="wwwroot\**" />
    <EmbeddedResource Remove="RenderableContentControl\**" />
    <EmbeddedResource Remove="wwwroot\**" />
    <None Remove="RenderableContentControl\**" />
    <None Remove="wwwroot\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\assets\icons\icon_128_128.png" Link="icon_128_128.png">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
    <None Include="..\..\..\NUGET-README.md" Link="NUGET-README.md">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

  
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>  
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />  
    <PackageReference Include="Operon" />  
    <PackageReference Include="System.Net.Http" />  
    <PackageReference Include="System.Text.Encodings.Web" />  
    <PackageReference Include="System.Text.RegularExpressions" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AXSharp.Presentation.Blazor\AXSharp.Presentation.Blazor.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<DefaultItemExcludes>$(DefaultItemExcludes);Operon\**\*</DefaultItemExcludes>
	</PropertyGroup>

</Project>
