NAMESPACE axosimple
    TYPE HwIdentifierList : ARRAY[0..15] OF UINT :=
            [
                UINT#32,
                UINT#48,
                UINT#51,
                UINT#54,
                UINT#64,
                UINT#65,
                UINT#66,
                UINT#72,
                UINT#73,
                UINT#74,
                UINT#117,
                UINT#120,
                UINT#121,
                UINT#135,
                UINT#256,
                UINT#257
    ];
END_TYPE
END_NAMESPACE

